######image: lwieske/java-8
image: airhacks/java

stages:       
  - testing
  
testing:
    stage: testing    
    
    script:
    - yum -y install wget
    - chmod 755 java_shell.sh
    - wget http://download.java.net/java/jdk9/archive/172/binaries/jdk-9-ea+172_linux-x64_bin.tar.gz
    - tar -xzf jdk-9-ea+172_linux-x64_bin.tar.gz
    - JAVA_HOME=./jdk-9
    - PATH=$JAVA_HOME/bin:$PATH
    - java -version
    - $JAVA_HOME/bin/jshell ./java_shell.sh